In [1]:
import pandas as pd
# Varies with sklearn version
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
from sklearn.externals import joblib

# Load the data set
df = pd.read_csv("ml_house_data_set.csv")

# Remove the fields from the data set that we don't want to include in our model
del df['house_number']
del df['unit_number']
del df['street_name']
del df['zip_code']

# Replace categorical data with one-hot encoded data
features_df = pd.get_dummies(df, columns=['garage_type', 'city'])

# Remove the sale price from the feature data
del features_df['sale_price']

# Create the X and y arrays
X = features_df.values
y = df['sale_price'].values

X,y



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


(array([[1978, 1, 4, ..., 0, 0, 0],
        [1958, 1, 3, ..., 0, 0, 0],
        [2002, 1, 3, ..., 0, 0, 0],
        ...,
        [1983, 1, 1, ..., 0, 0, 0],
        [1981, 1, 3, ..., 0, 0, 0],
        [1980, 1, 3, ..., 0, 0, 0]], dtype=object),
 array([ 270897.,  302404., 2519996., ...,   98280.,   98278.,  186480.]))

In [2]:
features_df.to_csv('SampleX1.csv')
df['sale_price'].to_csv('SampleY1.csv')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  


In [3]:
# Split the data set in a training set (70%) and a test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state = 43)

X_train, X_test, y_train, y_test 

(array([[2008, 1, 3, ..., 0, 0, 0],
        [2010, 2, 4, ..., 0, 0, 0],
        [2007, 2, 3, ..., 0, 0, 0],
        ...,
        [1909, 4, 5, ..., 0, 0, 0],
        [2006, 2, 3, ..., 0, 0, 0],
        [1971, 2, 5, ..., 0, 0, 0]], dtype=object),
 array([[2002, 1, 2, ..., 0, 0, 0],
        [2006, 1, 3, ..., 0, 0, 0],
        [1979, 1, 3, ..., 0, 0, 0],
        ...,
        [1957, 2, 2, ..., 0, 0, 0],
        [2004, 2, 5, ..., 0, 0, 0],
        [1943, 1, 3, ..., 0, 0, 0]], dtype=object),
 array([692999., 440999., 277200., ..., 226799., 527937., 487617.]),
 array([296103., 239401., 434696., ..., 313741., 655202., 239404.]))

In [5]:
# Fit regression model
model = ensemble.GradientBoostingRegressor(
    n_estimators=1000,
    learning_rate=0.1,
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss='huber',
    random_state=0
)
model.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='huber', max_depth=6,
                          max_features=0.1, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=9, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=1000,
                          n_iter_no_change=None, presort='auto', random_state=0,
                          subsample=1.0, tol=0.0001, validation_fraction=0.1,
                          verbose=0, warm_start=False)

In [8]:
#http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html

In [4]:
# Save the trained model to a file so we can use it in other programs
joblib.dump(model, 'model/trained_house_classifier_model.pkl')

NameError: name 'model' is not defined

In [10]:
# Find the error rate on the training set
mae = mean_absolute_error(y_train, model.predict(X_train))
print("Training Set Mean Absolute Error: %.4f" % mae)

# Find the error rate on the test set
mae = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: %.4f" % mae)

Training Set Mean Absolute Error: 47928.4595
Test Set Mean Absolute Error: 60093.5351


In [1]:
import numpy as np
from sklearn.externals import joblib

# These are the feature labels from our data set
feature_labels = np.array(['year_built', 'stories', 'num_bedrooms', 'full_bathrooms', 'half_bathrooms', 'livable_sqft', 'total_sqft', 'garage_sqft', 'carport_sqft', 'has_fireplace', 'has_pool', 'has_central_heating', 'has_central_cooling', 'garage_type_attached', 'garage_type_detached', 'garage_type_none', 'city_Amystad', 'city_Brownport', 'city_Chadstad', 'city_Clarkberg', 'city_Coletown', 'city_Davidfort', 'city_Davidtown', 'city_East Amychester', 'city_East Janiceville', 'city_East Justin', 'city_East Lucas', 'city_Fosterberg', 'city_Hallfort', 'city_Jeffreyhaven', 'city_Jenniferberg', 'city_Joshuafurt', 'city_Julieberg', 'city_Justinport', 'city_Lake Carolyn', 'city_Lake Christinaport', 'city_Lake Dariusborough', 'city_Lake Jack', 'city_Lake Jennifer', 'city_Leahview', 'city_Lewishaven', 'city_Martinezfort', 'city_Morrisport', 'city_New Michele', 'city_New Robinton', 'city_North Erinville', 'city_Port Adamtown', 'city_Port Andrealand', 'city_Port Daniel', 'city_Port Jonathanborough', 'city_Richardport', 'city_Rickytown', 'city_Scottberg', 'city_South Anthony', 'city_South Stevenfurt', 'city_Toddshire', 'city_Wendybury', 'city_West Ann', 'city_West Brittanyview', 'city_West Gerald', 'city_West Gregoryview', 'city_West Lydia', 'city_West Terrence'])

# Load the trained model created with train_model.py
model = joblib.load('model/trained_house_classifier_model.pkl')

# Create a numpy array based on the model's feature importances
importance = model.feature_importances_

# Sort the feature labels based on the feature importance rankings from the model
feauture_indexes_by_importance = importance.argsort()

# Print each feature label, from most important to least important (reverse order)
for index in feauture_indexes_by_importance:
    print("{} - {:.2f}%".format(feature_labels[index], (importance[index] * 100.0)))


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


city_New Robinton - 0.00%
city_New Michele - 0.00%
city_Martinezfort - 0.00%
city_Julieberg - 0.00%
city_Davidtown - 0.00%
city_Lake Jennifer - 0.00%
city_West Terrence - 0.01%
city_West Brittanyview - 0.01%
city_Rickytown - 0.01%
city_Fosterberg - 0.01%
city_East Justin - 0.01%
city_South Stevenfurt - 0.01%
city_Leahview - 0.03%
city_Toddshire - 0.03%
city_East Janiceville - 0.03%
city_Wendybury - 0.04%
city_Joshuafurt - 0.04%
city_Brownport - 0.04%
city_Amystad - 0.05%
city_Port Adamtown - 0.05%
city_Port Daniel - 0.05%
city_Clarkberg - 0.09%
city_West Lydia - 0.11%
garage_type_detached - 0.11%
city_Port Jonathanborough - 0.12%
city_Davidfort - 0.13%
city_West Gerald - 0.17%
has_central_cooling - 0.17%
city_Jenniferberg - 0.17%
city_East Amychester - 0.21%
city_Lewishaven - 0.22%
city_Lake Carolyn - 0.24%
city_North Erinville - 0.25%
city_Morrisport - 0.26%
city_East Lucas - 0.29%
has_central_heating - 0.29%
city_Lake Dariusborough - 0.36%
city_Richardport - 0.36%
city_West Gregoryvi

In [43]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.feature_selection import SelectFromModel






SelectFromModel(estimator=LinearRegression(copy_X=True, fit_intercept=True,
                                           n_jobs=None, normalize=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

ValueError: bad input shape (12811, 63)