In [1]:
def estimate_home_value(size_in_sqft, number_of_bedrooms):

    # Assume all homes are worth at least $50,000
    value = 50000

    # Adjust the value estimate based on the size of the house
    value = value + (size_in_sqft * 92.1)

    # Adjust the value estimate based on the number of bedrooms
    value = value + (number_of_bedrooms * 10000)

    return value

# Estimate the value of our house:
# - 5 bedrooms
# - 3800 sq ft
# Actual value: $450,000

value = estimate_home_value(3800, 5)

print("Estimated valued:")
print(value)

Estimated valued:
449980.0


In [1]:
import pandas
import webbrowser
import os

# Read the dataset into a data table using Pandas
data_table = pandas.read_csv("ml_house_data_set.csv")

# Create a web page view of the data for easy viewing
html = data_table[0:100].to_html()

# Save the html to a temporary file
with open("data.html", "w") as f:
    f.write(html)

# Open the web page in our web browser
full_filename = os.path.abspath("data.html")
webbrowser.open("file://{}".format(full_filename))

True

In [4]:
import pandas as pd
# Varies with sklearn version
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
from sklearn.externals import joblib

# Load the data set
df = pd.read_csv("ml_house_data_set.csv")

# Remove the fields from the data set that we don't want to include in our model
del df['house_number']
del df['unit_number']
del df['street_name']
del df['zip_code']

# Replace categorical data with one-hot encoded data
features_df = pd.get_dummies(df, columns=['garage_type', 'city'])

# Remove the sale price from the feature data
del features_df['sale_price']

# Create the X and y arrays
X = features_df.as_matrix()
y = df['sale_price'].as_matrix()

X,y

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


(array([[1978, 1, 4, ..., 0, 0, 0],
        [1958, 1, 3, ..., 0, 0, 0],
        [2002, 1, 3, ..., 0, 0, 0],
        ...,
        [1983, 1, 1, ..., 0, 0, 0],
        [1981, 1, 3, ..., 0, 0, 0],
        [1980, 1, 3, ..., 0, 0, 0]], dtype=object),
 array([ 270897.,  302404., 2519996., ...,   98280.,   98278.,  186480.]))

In [5]:
features_df.to_csv('SampleX.csv')
df['sale_price'].to_csv('SampleY.csv')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  


In [6]:
# Split the data set in a training set (70%) and a test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

X_train, X_test, y_train, y_test 

(array([[1988, 1, 3, ..., 0, 0, 0],
        [2006, 2, 4, ..., 0, 0, 0],
        [2004, 2, 4, ..., 0, 0, 0],
        ...,
        [1974, 2, 5, ..., 0, 0, 0],
        [2016, 2, 4, ..., 0, 0, 0],
        [2015, 1, 2, ..., 0, 0, 0]], dtype=object),
 array([[2006, 1, 3, ..., 0, 0, 0],
        [1974, 1, 3, ..., 0, 0, 0],
        [2007, 2, 2, ..., 0, 0, 0],
        ...,
        [2007, 1, 4, ..., 0, 0, 0],
        [1963, 1, 2, ..., 0, 0, 0],
        [1987, 1, 4, ..., 0, 0, 0]], dtype=object),
 array([332013., 428396., 623702., ..., 573297., 655196., 373593.]),
 array([364141., 447298., 245702., ...,  94496., 157502., 433442.]))

In [7]:
# Fit regression model
model = ensemble.GradientBoostingRegressor(
    n_estimators=1000,
    learning_rate=0.1,
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss='huber',
    random_state=0
)
model.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='huber', max_depth=6,
                          max_features=0.1, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=9, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=1000,
                          n_iter_no_change=None, presort='auto', random_state=0,
                          subsample=1.0, tol=0.0001, validation_fraction=0.1,
                          verbose=0, warm_start=False)

In [ ]:
#http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html

In [8]:
# Save the trained model to a file so we can use it in other programs
joblib.dump(model, 'model/trained_house_classifier_model.pkl')

['model/trained_house_classifier_model.pkl']

In [9]:
# Find the error rate on the training set
mae = mean_absolute_error(y_train, model.predict(X_train))
print("Training Set Mean Absolute Error: %.4f" % mae)

# Find the error rate on the test set
mae = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: %.4f" % mae)


Training Set Mean Absolute Error: 47577.9307
Test Set Mean Absolute Error: 59826.0662


In [1]:
import numpy as np
from sklearn.externals import joblib

# These are the feature labels from our data set
feature_labels = np.array(['year_built', 'stories', 'num_bedrooms', 'full_bathrooms', 'half_bathrooms', 'livable_sqft', 'total_sqft', 'garage_sqft', 'carport_sqft', 'has_fireplace', 'has_pool', 'has_central_heating', 'has_central_cooling', 'garage_type_attached', 'garage_type_detached', 'garage_type_none', 'city_Amystad', 'city_Brownport', 'city_Chadstad', 'city_Clarkberg', 'city_Coletown', 'city_Davidfort', 'city_Davidtown', 'city_East Amychester', 'city_East Janiceville', 'city_East Justin', 'city_East Lucas', 'city_Fosterberg', 'city_Hallfort', 'city_Jeffreyhaven', 'city_Jenniferberg', 'city_Joshuafurt', 'city_Julieberg', 'city_Justinport', 'city_Lake Carolyn', 'city_Lake Christinaport', 'city_Lake Dariusborough', 'city_Lake Jack', 'city_Lake Jennifer', 'city_Leahview', 'city_Lewishaven', 'city_Martinezfort', 'city_Morrisport', 'city_New Michele', 'city_New Robinton', 'city_North Erinville', 'city_Port Adamtown', 'city_Port Andrealand', 'city_Port Daniel', 'city_Port Jonathanborough', 'city_Richardport', 'city_Rickytown', 'city_Scottberg', 'city_South Anthony', 'city_South Stevenfurt', 'city_Toddshire', 'city_Wendybury', 'city_West Ann', 'city_West Brittanyview', 'city_West Gerald', 'city_West Gregoryview', 'city_West Lydia', 'city_West Terrence'])

# Load the trained model created with train_model.py
model = joblib.load('model/trained_house_classifier_model.pkl')

# Create a numpy array based on the model's feature importances
importance = model.feature_importances_

# Sort the feature labels based on the feature importance rankings from the model
feauture_indexes_by_importance = importance.argsort()

# Print each feature label, from most important to least important (reverse order)
for index in feauture_indexes_by_importance:
    print("{} - {:.2f}%".format(feature_labels[index], (importance[index] * 100.0)))


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


city_New Michele - 0.00%
city_Julieberg - 0.00%
city_New Robinton - 0.00%
city_Martinezfort - 0.00%
city_Lake Jennifer - 0.00%
city_Davidtown - 0.00%
city_Rickytown - 0.01%
city_South Stevenfurt - 0.01%
city_East Justin - 0.01%
city_West Brittanyview - 0.01%
city_West Terrence - 0.01%
city_Fosterberg - 0.01%
city_Leahview - 0.02%
city_Toddshire - 0.03%
city_Wendybury - 0.03%
city_Brownport - 0.03%
city_Port Adamtown - 0.04%
city_East Janiceville - 0.04%
city_Joshuafurt - 0.04%
city_Amystad - 0.05%
city_Port Daniel - 0.06%
city_Clarkberg - 0.08%
city_Port Jonathanborough - 0.12%
garage_type_detached - 0.12%
city_Jenniferberg - 0.16%
city_West Lydia - 0.18%
city_Davidfort - 0.18%
city_North Erinville - 0.23%
city_Lewishaven - 0.25%
city_East Amychester - 0.25%
city_East Lucas - 0.27%
city_Morrisport - 0.29%
city_West Gerald - 0.30%
city_West Gregoryview - 0.32%
city_Lake Dariusborough - 0.34%
city_Lake Carolyn - 0.35%
has_central_heating - 0.38%
city_Richardport - 0.38%
city_West Ann - 0

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
from sklearn.externals import joblib

# Load the data set
df = pd.read_csv("ml_house_data_set.csv")

# Remove the fields from the data set that we don't want to include in our model
del df['house_number']
del df['unit_number']
del df['street_name']
del df['zip_code']

# Replace categorical data with one-hot encoded data
features_df = pd.get_dummies(df, columns=['garage_type', 'city'])

# Remove the sale price from the feature data
del features_df['sale_price']

# Create the X and y arrays
X = features_df.as_matrix()
y = df['sale_price'].as_matrix()

# Split the data set in a training set (70%) and a test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Fit regression model
model = ensemble.GradientBoostingRegressor(
    n_estimators=1000,
    learning_rate=0.1,
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss='huber'
)
model.fit(X_train, y_train)

# Save the trained model to a file so we can use it in other programs
joblib.dump(model, 'model/trained_house_classifier_model.pkl')

# Find the error rate on the training set
mse = mean_absolute_error(y_train, model.predict(X_train))
print("Training Set Mean Absolute Error: %.4f" % mse)

# Find the error rate on the test set
mse = mean_absolute_error(y_test, model.predict(X_test))
print("Test Set Mean Absolute Error: %.4f" % mse)



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


Training Set Mean Absolute Error: 48618.2759
Test Set Mean Absolute Error: 58927.1341


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_absolute_error

# Load the data set
df = pd.read_csv("ml_house_data_set.csv")

# Remove the fields from the data set that we don't want to include in our model
del df['house_number']
del df['unit_number']
del df['street_name']
del df['zip_code']

# Replace categorical data with one-hot encoded data
features_df = pd.get_dummies(df, columns=['garage_type', 'city'])
del features_df['sale_price']

X = features_df.as_matrix()
y = df['sale_price'].as_matrix()

# Split the data set in a training set (70%) and a test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [11]:
# Fit regression model
regr_1 = DecisionTreeRegressor(max_depth=4)

regr_2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=50),n_estimators=70)

regr_1.fit(X_train, y_train)
regr_2.fit(X_train, y_train)

# Predict
y_1 = regr_1.predict(X_test)
y_2 = regr_2.predict(X_test)

mse = mean_absolute_error(y_test, y_1)
print("Mean Absolute Error (DT) : %.4f" % mse)

mse = mean_absolute_error(y_test, y_2)
print("Mean Absolute Error (AdaBoost) : %.4f" % mse)

Mean Absolute Error (DT) : 111283.3403
Mean Absolute Error (AdaBoost) : 59571.7507


In [13]:
from sklearn import linear_model

reg = linear_model.LinearRegression()
reg.fit (X_train,y_train)
pred=reg.predict(X_test)
mse = mean_absolute_error(y_test,pred)
print("Mean Absolute Error : %.4f" % mse)

Mean Absolute Error : 96230.1727


In [14]:
from sklearn.linear_model import SGDRegressor

reg = linear_model.SGDRegressor()
reg.fit (X_train,y_train)
pred=reg.predict(X_test)
mse = mean_absolute_error(y_test,pred)
print("Mean Absolute Error : %.4f" % mse)


Mean Absolute Error : 7819301843446930.0000


In [15]:
#Let's find if it underfits...
# Find the error rate on the training set
mse = mean_absolute_error(y_train, reg.predict(X_train))
print("Training Set Mean Absolute Error: %.4f" % mse)

# Find the error rate on the test set
mse = mean_absolute_error(y_test, reg.predict(X_test))
print("Test Set Mean Absolute Error: %.4f" % mse)

Training Set Mean Absolute Error: 7769785249299518.0000
Test Set Mean Absolute Error: 7819301843446930.0000


In [16]:
from sklearn.ensemble import RandomForestRegressor

reg = RandomForestRegressor()
reg.fit (X_train,y_train)
pred=reg.predict(X_test)
mse = mean_absolute_error(y_test,pred)
print("Mean Absolute Error : %.4f" % mse)

Mean Absolute Error : 64752.4880


In [17]:
## Naive Bayes

from sklearn.linear_model import BayesianRidge

reg = BayesianRidge()
reg.fit (X_train,y_train)
pred=reg.predict(X_test)
mse = mean_absolute_error(y_test,pred)
print("Mean Absolute Error : %.4f" % mse)

Mean Absolute Error : 96231.9639


In [18]:
from sklearn.svm import SVR

reg = SVR()
reg.fit (X_train,y_train)
pred=reg.predict(X_test)
mse = mean_absolute_error(y_test,pred)
print("Mean Absolute Error : %.4f" % mse)

Mean Absolute Error : 171395.1292


In [ ]:
import pandas
from sklearn import ensemble
from sklearn.cross_validation import train_test_split
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import mean_absolute_error
from sklearn.cross_validation import train_test_split

# Load the data set
df = pandas.read_csv("ml_house_data_set.csv")

# Remove the fields from the data set that we don't want to include in our model
del df['house_number']
del df['unit_number']
del df['street_name']
del df['zip_code']

# Replace categorical data with one-hot encoded data
features_df = pandas.get_dummies(df, columns=['garage_type', 'city'])
del features_df['sale_price']

X = features_df.as_matrix()
y = df['sale_price'].as_matrix()

# Split the data set in a training set (70%) and a test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Create the model
model = ensemble.GradientBoostingRegressor()

# Parameters we want to try
param_grid = {
    'n_estimators': [500, 3000],
    'max_depth': [4, 6],
    'min_samples_leaf': [3, 9],
    'learning_rate': [0.1, 0.05],
    'max_features': [0.3, 0.1],
    'loss': ['ls', 'huber']
}

#param_grid = {
#    'n_estimators': [500, 1000, 3000],
#    'max_depth': [4, 6],
#   'min_samples_leaf': [3, 5, 9, 17],
#    'learning_rate': [0.1, 0.05, 0.02, 0.01],
#    'max_features': [1.0, 0.3, 0.1],
#    'loss': ['ls', 'lad', 'huber']
#}

# Define the grid search we want to run. Run it with four cpus in parallel. -1 all cores
gs_cv = GridSearchCV(model, param_grid, n_jobs=-1)

# Run the grid search - on only the training data!
gs_cv.fit(X_train, y_train)

# Print the parameters that gave us the best result!
print(gs_cv.best_params_)

# After running a .....long..... time, the output will be something like
# {'loss': 'huber', 'learning_rate': 0.1, 'min_samples_leaf': 9, 'n_estimators': 3000, 'max_features': 0.1, 'max_depth': 6}

# That is the combination that worked best.

# Find the error rate on the training set using the best parameters
mse = mean_absolute_error(y_train, gs_cv.predict(X_train))
print("Training Set Mean Absolute Error: %.4f" % mse)

# Find the error rate on the test set using the best parameters
mse = mean_absolute_error(y_test, gs_cv.predict(X_test))
print("Test Set Mean Absolute Error: %.4f" % mse)



C:\ProgramData\Anaconda2\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


Other Datasets
Auto MPG : https://archive.ics.uci.edu/ml/datasets/auto+mpg
    
Auto MPG CSV format : https://www.kaggle.com/uciml/autompg-dataset    
        
Bike Sharing : https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset
        
Actual Feed: https://www.motivateco.com/use-our-data/
        
CSV Format: https://www.kaggle.com/marklvl/bike-sharing-dataset